<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $listuser = [
            ['name' =>"KAHAR ABDUL BIN AHMAD"           ,"email" =>"kahar@yopmail.com"      ,"ic_number"=>"600101015333"  ,"date_of_birth"=>"18/6/1990"   ,"gender"=>"F", "race"=>"Chinese"   ,"religion"=>"Christianity"     ,"permanent_address1"=>"789 Taman Desa"            ,"permanent_address2"=>"Apt 12B"   ,"permanent_address3"=>"Petaling Jaya"  ,"permanent_address_postcode"=>"47301"  ,"permanent_address_city_code"=>"PJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'1'  ],
            ['name' =>"NORAAINI BINTI HASHIM"           ,"email" =>"noraaini@yopmail.com"   ,"ic_number"=>"600101015776"  ,"date_of_birth"=>"17/4/2000"   ,"gender"=>"F", "race"=>"Malay"     ,"religion"=>"Islam"            ,"permanent_address1"=>"789 Taman Desa"            ,"permanent_address2"=>"Apt 12B"   ,"permanent_address3"=>"Petaling Jaya"  ,"permanent_address_postcode"=>"47301"  ,"permanent_address_city_code"=>"PJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'1'  ],
            ['name' =>"A'ISHAH BINTI ISMAIL"            ,"email" =>"aishah@yopmail.com"     ,"ic_number"=>"600101015884"  ,"date_of_birth"=>"7/4/1961"    ,"gender"=>"F", "race"=>"Others"    ,"religion"=>"Islam"            ,"permanent_address1"=>"789 Taman Desa"            ,"permanent_address2"=>"Apt 12B"   ,"permanent_address3"=>"Petaling Jaya"	,"permanent_address_postcode"=>"47301"  ,"permanent_address_city_code"=>"PJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'1'  ],
            ['name' =>"BAHARI BIN A MAJID"              ,"email" =>"bahari@morgan.org"      ,"ic_number"=>"600101015155"  ,"date_of_birth"=>"26/3/1946"   ,"gender"=>"F", "race"=>"Malay"     ,"religion"=>"Christianity"     ,"permanent_address1"=>"789 Taman Desa"            ,"permanent_address2"=>"Apt 12B"   ,"permanent_address3"=>"Petaling Jaya"	,"permanent_address_postcode"=>"47301"  ,"permanent_address_city_code"=>"PJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'1'  ],
            ['name' =>"NOOR ZURAIDAH BINTI MOKHLAS"     ,"email" =>"zuraidah@hotmail.com"   ,"ic_number"=>"810101085224"  ,"date_of_birth"=>"26/12/1980"  ,"gender"=>"M", "race"=>"Indian"    ,"religion"=>"Islam"            ,"permanent_address1"=>"789 Taman Desa"            ,"permanent_address2"=>"Apt 12B"   ,"permanent_address3"=>"Petaling Jaya"  ,"permanent_address_postcode"=>"47301"  ,"permanent_address_city_code"=>"PJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'A'  ],
            ['name' =>"AHMAD BIN SANI"                  ,"email" =>"ahmad@example.com"	    ,"ic_number"=>"600201716159"  ,"date_of_birth"=>"15/5/1980"   ,"gender"=>"M", "race"=>"Malay"     ,"religion"=>"Islam"            ,"permanent_address1"=>"123 Jalan Ampang"          ,"permanent_address2"=>"Apt 12B"	,"permanent_address3"=>"Kuala Lumpur"   ,"permanent_address_postcode"=>"50450"  ,"permanent_address_city_code"=>"KL"    ,"permanent_address_state_code"=>"KL"   ,"residential_status"=>'P'   ,"record_status"=>'1'  ],
            ['name' =>"ZAMRI BIN MD ISA"                ,"email" =>"zamri@ortiz.com"	    ,"ic_number"=>"700205025101"  ,"date_of_birth"=>"26/11/1991"  ,"gender"=>"M", "race"=>"Others"    ,"religion"=>"Christianity"     ,"permanent_address1"=>"123 Jalan Ampang"          ,"permanent_address2"=>"Apt 12B"	,"permanent_address3"=>"Kuala Lumpur"   ,"permanent_address_postcode"=>"50450"  ,"permanent_address_city_code"=>"KL"    ,"permanent_address_state_code"=>"KL"   ,"residential_status"=>'B'   ,"record_status"=>'1'  ],
            ['name' =>"AHMAD BIN HISHAM"                ,"email" =>"ahmadh@yahoo.com"	    ,"ic_number"=>"600101015259"  ,"date_of_birth"=>"13/5/1968"   ,"gender"=>"M", "race"=>"Others"    ,"religion"=>"Buddhism"         ,"permanent_address1"=>"123 Jalan Ampang"          ,"permanent_address2"=>"Apt 12B"	,"permanent_address3"=>"Kuala Lumpur"   ,"permanent_address_postcode"=>"50450"  ,"permanent_address_city_code"=>"KL"    ,"permanent_address_state_code"=>"KL"   ,"residential_status"=>'C'   ,"record_status"=>'1'  ],
            ['name' =>"ZAKARIA BIN MOHD NOR"            ,"email" =>"zakaria@sharp.com"	    ,"ic_number"=>"700101712555"  ,"date_of_birth"=>"23/2/1946"   ,"gender"=>"F", "race"=>"Malay"     ,"religion"=>"Islam"            ,"permanent_address1"=>"123 Jalan Ampang"          ,"permanent_address2"=>"Apt 12B"	,"permanent_address3"=>"Kuala Lumpur"	,"permanent_address_postcode"=>"50450"  ,"permanent_address_city_code"=>"KL"    ,"permanent_address_state_code"=>"KL"   ,"residential_status"=>'M'   ,"record_status"=>'1'  ],
            ['name' =>"SUHAILA BINTI SAGHIL @ YUSOF"    ,"email" =>"suhaila@turner.biz"	    ,"ic_number"=>"850622087816"  ,"date_of_birth"=>"17/9/1963"   ,"gender"=>"M", "race"=>"Others"    ,"religion"=>"None"             ,"permanent_address1"=>"123 Jalan Ampang"          ,"permanent_address2"=>"Apt 12B"	,"permanent_address3"=>"Kuala Lumpur"	,"permanent_address_postcode"=>"50450"  ,"permanent_address_city_code"=>"KL"    ,"permanent_address_state_code"=>"KL"   ,"residential_status"=>'B'   ,"record_status"=>'1'  ],
            ['name' =>"HARI DASS A/L PANCHANATHAN"      ,"email" =>"haridass@example.com"	,"ic_number"=>"830605127571"  ,"date_of_birth"=>"25/3/1975"   ,"gender"=>"M", "race"=>"Indian"    ,"religion"=>"Hinduism"         ,"permanent_address1"=>"56 Lorong Damansara"       ,"permanent_address2"=>"Blk A5"	,"permanent_address3"=>"Subang Jaya"    ,"permanent_address_postcode"=>"47500"  ,"permanent_address_city_code"=>"SJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'1'  ],
            ['name' =>"JANAIDI BIN MUNIR"               ,"email" =>"janaidi@hotmail.com"	,"ic_number"=>"700101715555"  ,"date_of_birth"=>"11/5/1983"   ,"gender"=>"M", "race"=>"Indian"    ,"religion"=>"Christianity"     ,"permanent_address1"=>"56 Lorong Damansara"       ,"permanent_address2"=>"Blk A5"	,"permanent_address3"=>"Subang Jaya"    ,"permanent_address_postcode"=>"47500"  ,"permanent_address_city_code"=>"SJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'M'   ,"record_status"=>'1'  ],
            ['name' =>"MASHURI BIN KATMIN"              ,"email" =>"mashuri@hotmail.com"	,"ic_number"=>"600101015117"  ,"date_of_birth"=>"10/9/1955"   ,"gender"=>"F", "race"=>"Others"    ,"religion"=>"Hinduism"         ,"permanent_address1"=>"56 Lorong Damansara"       ,"permanent_address2"=>"Blk A5"	,"permanent_address3"=>"Subang Jaya"    ,"permanent_address_postcode"=>"47500"  ,"permanent_address_city_code"=>"SJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'2'  ],
            ['name' =>"PIRIN BIN JAMIRO"                ,"email" =>"pirin@hotmail.com"	    ,"ic_number"=>"400101015661"  ,"date_of_birth"=>"14/11/1995"  ,"gender"=>"F", "race"=>"Others"    ,"religion"=>"None"             ,"permanent_address1"=>"56 Lorong Damansara"       ,"permanent_address2"=>"Blk A5"	,"permanent_address3"=>"Subang Jaya"	,"permanent_address_postcode"=>"47500"  ,"permanent_address_city_code"=>"SJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'2'  ],
            ['name' =>"ABDUL RAHMAN BIN IBRAHIM"        ,"email" =>"arahman@yopmail.com"	,"ic_number"=>"560106015331"  ,"date_of_birth"=>"24/12/1936"  ,"gender"=>"M", "race"=>"Chinese"   ,"religion"=>"Christianity"     ,"permanent_address1"=>"56 Lorong Damansara"       ,"permanent_address2"=>"Blk A5"	,"permanent_address3"=>"Subang Jaya"	,"permanent_address_postcode"=>"47500"  ,"permanent_address_city_code"=>"SJ"    ,"permanent_address_state_code"=>"SGR"  ,"residential_status"=>'B'   ,"record_status"=>'2'  ],
            ['name' =>"AHMAD BIN MUSTAPHA"              ,"email" =>"amustapha@example.com"	,"ic_number"=>"610805715059"  ,"date_of_birth"=>"30/8/1991"   ,"gender"=>"M", "race"=>"Chinese"   ,"religion"=>"Buddhism"         ,"permanent_address1"=>"14 Jalan Ria"              ,"permanent_address2"=>"Apt 7D"	,"permanent_address3"=>"Ipoh"           ,"permanent_address_postcode"=>"30000"  ,"permanent_address_city_code"=>"IP"    ,"permanent_address_state_code"=>"IPH"  ,"residential_status"=>'P'   ,"record_status"=>'2'  ],
            ['name' =>"SITTI NOORIJAH BINTI JAMALUDDIN" ,"email" =>"noorijah@hotmail.com"	,"ic_number"=>"800101126666"  ,"date_of_birth"=>"22/4/1935"   ,"gender"=>"M", "race"=>"Malay"     ,"religion"=>"Hinduism"         ,"permanent_address1"=>"14 Jalan Ria"              ,"permanent_address2"=>"Apt 7D"	,"permanent_address3"=>"Ipoh"           ,"permanent_address_postcode"=>"30000"  ,"permanent_address_city_code"=>"IP"    ,"permanent_address_state_code"=>"IPH"  ,"residential_status"=>'H'   ,"record_status"=>null ],
            ['name' =>"KHAMSANI BIN SAHID"              ,"email" =>"khamsani@gmail.com"	    ,"ic_number"=>"800103125999"  ,"date_of_birth"=>"30/8/2000"   ,"gender"=>"F", "race"=>"Indian"    ,"religion"=>"Hinduism"         ,"permanent_address1"=>"14 Jalan Ria"              ,"permanent_address2"=>"Apt 7D"	,"permanent_address3"=>"Ipoh"           ,"permanent_address_postcode"=>"30000"  ,"permanent_address_city_code"=>"IP"    ,"permanent_address_state_code"=>"IPH"  ,"residential_status"=>'H'   ,"record_status"=>null ],
            ['name' =>"MAZLAN BIN MUBIN"                ,"email" =>"mazlan@vargas.com"	    ,"ic_number"=>"900415827777"  ,"date_of_birth"=>"9/12/1976"   ,"gender"=>"M", "race"=>"Malay"     ,"religion"=>"Islam"            ,"permanent_address1"=>"14 Jalan Ria"              ,"permanent_address2"=>"Apt 7D"	,"permanent_address3"=>"Ipoh"	        ,"permanent_address_postcode"=>"30000"  ,"permanent_address_city_code"=>"IP"    ,"permanent_address_state_code"=>"IPH"  ,"residential_status"=>'Q'   ,"record_status"=>null ],
            ['name' =>"FAZILAH BINTI ISAH"              ,"email" =>"fazilah@example.com"	,"ic_number"=>"900428825444"  ,"date_of_birth"=>"12/12/1982"  ,"gender"=>"F", "race"=>"Malay" 	  ,"religion"=>"Islam"            ,"permanent_address1"=>"101 Jalan Merdeka"         ,"permanent_address2"=>"House 2"	,"permanent_address3"=>"Melaka"         ,"permanent_address_postcode"=>"75000"  ,"permanent_address_city_code"=>"MK"    ,"permanent_address_state_code"=>"MLK"  ,"residential_status"=>'Q'   ,"record_status"=>null ],
            ['name' =>"KAIRULNAS BIN NAWASIR"           ,"email" =>"khairulnas@brown.org"	,"ic_number"=>"700101615555"  ,"date_of_birth"=>"31/10/1983"  ,"gender"=>"M", "race"=>"Indian"    ,"religion"=>"Islam"            ,"permanent_address1"=>"101 Jalan Merdeka"         ,"permanent_address2"=>"House 2"	,"permanent_address3"=>"Melaka"         ,"permanent_address_postcode"=>"75000"  ,"permanent_address_city_code"=>"MK"    ,"permanent_address_state_code"=>"MLK"  ,"residential_status"=>'X'   ,"record_status"=>null ],
            ['name' =>"HYDRALI BIN HYDROSE"             ,"email" =>"hydrali@gmail.com"	    ,"ic_number"=>"700110015333"  ,"date_of_birth"=>"12/2/2002"   ,"gender"=>"F", "race"=>"Chinese"   ,"religion"=>"None"             ,"permanent_address1"=>"101 Jalan Merdeka"         ,"permanent_address2"=>"House 2"	,"permanent_address3"=>"Melaka"         ,"permanent_address_postcode"=>"75000"  ,"permanent_address_city_code"=>"MK"    ,"permanent_address_state_code"=>"MLK"  ,"residential_status"=>null  ,"record_status"=>null ],
            ['name' =>"SITI WAN KEMBANG"                ,"email" =>"wankembang@hill.com"	,"ic_number"=>"900415828888"  ,"date_of_birth"=>"13/10/1941"  ,"gender"=>"F", "race"=>"Indian"    ,"religion"=>"Buddhism"         ,"permanent_address1"=>"101 Jalan Merdeka"         ,"permanent_address2"=>"House 2"	,"permanent_address3"=>"Melaka"	        ,"permanent_address_postcode"=>"75000"  ,"permanent_address_city_code"=>"MK"    ,"permanent_address_state_code"=>"MLK"  ,"residential_status"=>null  ,"record_status"=>null ],
            ['name' =>"NORLELA BINTI AHMAD"             ,"email" =>"norlela@hotmail.com"	,"ic_number"=>"020309075018"  ,"date_of_birth"=>"19/4/1970"   ,"gender"=>"F", "race"=>"Indian"    ,"religion"=>"Islam"            ,"permanent_address1"=>"101 Jalan Merdeka"         ,"permanent_address2"=>"House 2"	,"permanent_address3"=>"Melaka"	        ,"permanent_address_postcode"=>"75000"  ,"permanent_address_city_code"=>"MK"    ,"permanent_address_state_code"=>"MLK"  ,"residential_status"=>null  ,"record_status"=>null ],
            ['name' =>"HARIADI BIN MOHD SAAD"           ,"email" =>"hariadi@hotmail.com"	,"ic_number"=>"810803125099"  ,"date_of_birth"=>"19/4/1970"   ,"gender"=>"F", "race"=>"Indian"    ,"religion"=>"Islam"            ,"permanent_address1"=>"101 Jalan Merdeka"         ,"permanent_address2"=>"House 2"	,"permanent_address3"=>"Melaka"	        ,"permanent_address_postcode"=>"75000"  ,"permanent_address_city_code"=>"MK"    ,"permanent_address_state_code"=>"MLK"  ,"residential_status"=>null  ,"record_status"=>null ],
            ['name' =>"ABDUL KARIM BIN DAMIT"           ,"email" =>"akarim@hotmail.com"	    ,"ic_number"=>"391215131119"  ,"date_of_birth"=>"19/4/1970"   ,"gender"=>"F", "race"=>"Indian"    ,"religion"=>"Islam"            ,"permanent_address1"=>"101 Jalan Merdeka"         ,"permanent_address2"=>"House 2"	,"permanent_address3"=>"Melaka"	        ,"permanent_address_postcode"=>"75000"  ,"permanent_address_city_code"=>"MK"    ,"permanent_address_state_code"=>"MLK"  ,"residential_status"=>null  ,"record_status"=>null ],
        ];
        foreach ($listuser as $key => $value) {
            $listuser[$key]["date_of_birth"] = Carbon::createFromFormat('d/m/Y', $value["date_of_birth"])->format('Y-m-d');
        }

        User::insert($listuser);
    }
}
